import { ALL_RULES, type Rule } from '@portfolio-lint/core'
import { textTable } from '../render/table.js'
import { mdTable } from '../render/markdown.js'

export function renderRulesTable(rules: readonly Rule[] = ALL_RULES): string {
  return (
    textTable(
      ['rule', 'dimension', 'weight', 'forecasts', 'description'],
      rules.map((r) => [r.id, r.dimension, String(r.weight), r.forecasts.join(','), r.description]),
    ) + '\n'
  )
}

export function renderRulesMarkdown(rules: readonly Rule[] = ALL_RULES): string {
  const out: string[] = []
  out.push('# Rules')
  out.push('')
  out.push('Generated by `portfolio-lint rules --format md`. Do not edit by hand.')
  out.push('')
  out.push('Each rule scores `100 * (1 - violations / applicable)`. Rules with zero applicable items are skipped.')
  out.push('Weights (1 to 3) drive the dimension score. Forecasts list which forecast types the rule degrades.')
  out.push('')
  out.push(
    mdTable(
      ['Rule', 'Dimension', 'Weight', 'Forecasts', 'Description'],
      rules.map((r) => [`[${r.id}](#${r.id})`, r.dimension, String(r.weight), r.forecasts.join(', '), r.description]),
    ),
  )
  out.push('')
  for (const r of rules) {
    out.push(`## ${r.id}`)
    out.push('')
    out.push(`- Dimension: ${r.dimension}`)
    out.push(`- Weight: ${r.weight}`)
    out.push(`- Forecasts affected: ${r.forecasts.join(', ')}`)
    out.push(`- Description: ${r.description}`)
    out.push(`- Forecast impact: ${r.forecastImpact}`)
    out.push(`- Remediation: ${r.remediation}`)
    out.push('')
  }
  return out.join('\n')
}
