import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { parsePortfolioCsv } from '../src/csv.js'
import { lintPortfolio } from '../src/report.js'

const here = dirname(fileURLToPath(import.meta.url))
const ERP = readFileSync(resolve(here, '../../../examples/erp-portfolio.csv'), 'utf8')
const NOW = '2026-08-24T00:00:00Z'

describe('erp-portfolio example (generated by scripts/gen-erp-portfolio.mjs)', () => {
  it('parses cleanly at scale', () => {
    const { portfolio, warnings, rowsSkipped } = parsePortfolioCsv(ERP, { name: 'erp', scannedAt: NOW })
    expect(warnings).toEqual([])
    expect(rowsSkipped).toBe(0)
    expect(portfolio.projects).toHaveLength(8)
    const total = portfolio.projects.reduce((n, p) => n + p.items.length, 0)
    expect(total).toBeGreaterThan(3000)
    // dependency chains inside and across projects
    const withDeps = portfolio.projects.flatMap((p) => p.items).filter((i) => i.dependsOn.length > 0)
    expect(withDeps.length).toBeGreaterThan(2000)
  })

  it('lints in well under a second and exercises every rule', () => {
    const { portfolio } = parsePortfolioCsv(ERP, { name: 'erp', scannedAt: NOW })
    const t0 = performance.now()
    const report = lintPortfolio(portfolio, { now: NOW })
    expect(performance.now() - t0).toBeLessThan(1000)
    const rulesHit = new Set(report.violations.map((v) => v.ruleId))
    expect(rulesHit.size).toBe(12)
    expect(report.score).toBeGreaterThan(50)
    expect(report.score).toBeLessThan(95)
  })
})
