import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { parsePortfolioCsv } from '../src/csv.js'
import { lintPortfolio } from '../src/report.js'

const here = dirname(fileURLToPath(import.meta.url))
const ERP = readFileSync(resolve(here, '../../../examples/erp-portfolio.csv'), 'utf8')
const NOW = '2026-08-24T00:00:00Z'

describe('erp-portfolio example (generated by scripts/gen-erp-portfolio.mjs)', () => {
  it('parses cleanly at scale', () => {
    const { portfolio, warnings, rowsSkipped } = parsePortfolioCsv(ERP, { name: 'erp', scannedAt: NOW })
    expect(warnings).toEqual([])
    expect(rowsSkipped).toBe(0)
    expect(portfolio.projects).toHaveLength(8)
    const total = portfolio.projects.reduce((n, p) => n + p.items.length, 0)
    expect(total).toBeGreaterThan(3000)
    // dependency chains inside and across projects
    const withDeps = portfolio.projects.flatMap((p) => p.items).filter((i) => i.dependsOn.length > 0)
    expect(withDeps.length).toBeGreaterThan(2000)
  })

  it('lints in well under a second and exercises every rule', () => {
    const { portfolio } = parsePortfolioCsv(ERP, { name: 'erp', scannedAt: NOW })
    const t0 = performance.now()
    const report = lintPortfolio(portfolio, { now: NOW })
    expect(performance.now() - t0).toBeLessThan(1000)
    const rulesHit = new Set(report.violations.map((v) => v.ruleId))
    expect(rulesHit.size).toBe(13)
    expect(report.violations.filter((v) => v.ruleId === 'dependency-cycle').length).toBeGreaterThan(0)
    expect(report.score).toBeGreaterThan(50)
    expect(report.score).toBeLessThan(95)
  })

  it('resolves cross-project dependencies instead of flagging them as broken', () => {
    const { portfolio } = parsePortfolioCsv(ERP, { name: 'erp', scannedAt: NOW })
    const report = lintPortfolio(portfolio, { now: NOW })
    const broken = report.violations.filter((v) => v.ruleId === 'broken-dependency')
    const allIds = new Set(portfolio.projects.flatMap((p) => p.items.map((i) => i.id)))
    // every remaining broken link points outside the whole scan, not just outside its project
    for (const v of broken) {
      const item = portfolio.projects.flatMap((p) => p.items).find((i) => i.key === v.itemKey)!
      expect(item.dependsOn.some((d) => !allIds.has(d))).toBe(true)
    }
  })

  it('produces a delivery forecast per project with a critical path', () => {
    const { portfolio } = parsePortfolioCsv(ERP, { name: 'erp', scannedAt: NOW })
    const report = lintPortfolio(portfolio, { now: NOW })
    const f = report.forecast!
    expect(f.projects).toHaveLength(8)
    expect(f.programme.p85).not.toBeNull()
    for (const p of f.projects) {
      expect(p.status).toBe('ok')
      expect(p.finish!.p50.weeks).toBeLessThanOrEqual(p.finish!.p85.weeks)
      expect(p.finish!.p85.weeks).toBeLessThanOrEqual(p.finish!.p95.weeks)
      expect(p.criticalPath.items.length).toBeGreaterThanOrEqual(1)
      expect(['high', 'medium', 'low']).toContain(p.confidence.level)
    }
    // dirty estimates translate into weeks of uncertainty the user can remove
    const pmo = f.projects.find((p) => p.key === 'ERPPMO')!
    expect(pmo.scopeUncertaintyWeeks).toBeGreaterThan(0)
    expect(pmo.confidence.level).toBe('low')
    expect(f.projects.some((p) => p.criticalPath.crossProject)).toBe(true)
    // deterministic: same seed, same numbers
    const again = lintPortfolio(portfolio, { now: NOW }).forecast!
    expect(again.projects.map((p) => p.finish!.p85.weeks)).toEqual(f.projects.map((p) => p.finish!.p85.weeks))
  })
})
